version: '3.7'

services:
  db:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: apple
      MYSQL_USER: domjudge
      MYSQL_DATABASE: domjudge
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
